services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: todos
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todopass
      MYSQL_ROOT_PASSWORD: rootpass # Cambia esto por una contraseña más segura si es necesario
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
